# Outputs generated by Terraform - Will be used by drift generator
output "test_bucket_name" { value = module.storage.test_bucket_name }
output "test_bucket_arn"  { value = module.storage.test_bucket_arn }